@prefix = {{host}}/api/v1

### user:find
GET {{prefix}}/user
content-type: application/json

### user:create
POST {{prefix}}/user
content-type: application/json

{
    // "id": "1",
    "avatar": "0000",
    "email": "{{$random.alphabetic(10)}}@noa.com",
    "password": "a123123.",
    "name": 123123
}

### user:update
PUT {{prefix}}/user/01JNZ1Z668P52NZ6VBX28Y5X7Q
content-type: application/json

{
    "avatar": "1233"
}

### user:delete
DELETE {{prefix}}/user/01JNZ1Z668P52NZ6VBX28Y5X7Q
content-type: application/json
