# 根目录请求
@baseUrl = {{hostname}}/auth

### 注册
# @name Register
POST  {{baseUrl}}/register
Content-Type: application/json

{
    "username": "eggvideo",
    "password": "eggvideo",
    "email": "eggvideo@gmail.com"
}

### 登录
# @name Login
POST  {{baseUrl}}/login
Content-Type: application/json

{
    "email": "eggvideo@gmail.com",
    "password": "eggvideo"
}
