@prefixUrl = http://localhost:19981
{{
  exports.defaultHeaders = {
    'x-test-req': 1
  };
}}
### getVerifyCode
GET {{prefixUrl}}/api/verify/code?width=200&height=50&type=login&svg=false

### register
@username = {{$random.alphabetic()}}
POST {{prefixUrl}}/api/auth/register
content-type: application/json
{
  "nickname": "{{username}}",
  "email": "{{username}}@gmail.com",
  "password": "123123",
  "verifyCode": "bnA7",
  "verifyCodeId": "code01JQNF0FPB8Q7NCNFXTSSD7BVE"
}

### login
POST {{prefixUrl}}/api/auth/login
content-type: application/json

{
  "email": "moUGBnvDLv@gmail.com",
  "password": "123123",
  "verifyCode": "8drx",
  "verifyCodeId": "code01JQNG5H2X5PRWW8BKE425H65E"
}

### video:create
POST {{prefixUrl}}/api/video
content-type: application/json
{
}

